// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ReservaQuadras.Models;
using System;

namespace ReservaQuadras.Migrations
{
    [DbContext(typeof(ReservaQuadraContext))]
    [Migration("20180822181924_Teste")]
    partial class Teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReservaQuadras.Models.Atletica", b =>
                {
                    b.Property<int>("AtleticaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("AtleticaID");

                    b.ToTable("Atleticas");
                });

            modelBuilder.Entity("ReservaQuadras.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Vinculo")
                        .IsRequired();

                    b.HasKey("PessoaID");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ReservaQuadras.Models.PessoaAtletica", b =>
                {
                    b.Property<int>("PessoaAtleticaID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AtleticaID");

                    b.Property<int>("PessoaID");

                    b.HasKey("PessoaAtleticaID");

                    b.HasIndex("AtleticaID");

                    b.HasIndex("PessoaID");

                    b.ToTable("PessoaAtleticas");
                });

            modelBuilder.Entity("ReservaQuadras.Models.PessoaAtletica", b =>
                {
                    b.HasOne("ReservaQuadras.Models.Atletica", "Atletica")
                        .WithMany("PessoaAtletica")
                        .HasForeignKey("AtleticaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReservaQuadras.Models.Pessoa", "Pessoa")
                        .WithMany("PessoaAtletica")
                        .HasForeignKey("PessoaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
